spring:
  application:
    name: notification-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411
  tracing:
    sampling:
      probability: 1

server:
  port: 0